server:
  port: 9595

spring:
  application:
    name: SmartShowcase-service
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5733/catalog-db
    username: postgres
    password: qwerty123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true



path:
    image: "src/main/resources/image"